### ISSUE TITLE
Add fts-rest

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/DIRACOS2#10]
@chaen Has there been any news on the state of fts-rest and Python 3?

**Comment by chaen** [comment]
Summarizing the info I gathered:

> The latest release `3.10` is compatible with python 3. The RC was done 3 days ago https://fts.web.cern.ch/fts/releases.html Plan is to have it in stable repo and pypi in 2 weeks.

**Comment by chaen** [comment]
it's here btw https://gitlab.cern.ch/fts/fts-rest-flask/-/tree/develop/

**Comment by chrisburr** [comment]
@chaen Any more news on this?

**Comment by chaen** [comment]
It's ready for release, but not actually released (other priorities, asked by me, sorry :-p )

**Comment by fstagni** [comment]
Revert https://github.com/DIRACGrid/DIRAC/pull/4975 once this is resolved.

**Comment by chaen** [comment]
Although not containing my MR yet, it was deployed as `fts3` on `pypi`. I'll update my MR to reflect that

**Comment by chrisburr** [comment]
As of v2.16 this is done! 🎉 

https://github.com/DIRACGrid/DIRACOS2/issues/10#issuecomment-781252602 [was dealt with already](https://github.com/DIRACGrid/DIRAC/commit/81169d8af713139ff6c842e17c27c1ddeaf37890).
