### ISSUE TITLE
Files not found when sourcing diracosrc with latest diracos release

### ISSUE THREAD

**Issue by maxnoe** [DIRACGrid/DIRACOS2#103]
After running the installation script, sourcing the `diracosrc` gives the following errors:

```
$ source ~/.local/diracos/diracosrc 
realpath: '': No such file or directory
realpath: /etc/grid-security/certificates: No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
```

**Comment by fstagni** [comment]
@chaen I think this is the result of https://github.com/DIRACGrid/DIRACOS2/pull/97. Can you have a look?

**Comment by chaen** [comment]
It's already fixed in https://github.com/DIRACGrid/DIRACOS2/pull/98
