### ISSUE TITLE
Prompt problems with DIRACOS v2.34

### ISSUE THREAD

**Issue by sfayer** [DIRACGrid/DIRACOS2#109]
Hi,

We've noticed that the latest DIRACOS seems to have trouble with the default prompt on RHEL. When the diracosrc is sourced, the prompt gets set to just "(base) " with the old prompt going missing:
```bash
[user@host dirac_dir]$ source diracos/diracosrc 
(base) # Where did my prompt go?
(base) 
```
The old behaviour was to keep the old prompt, e.g.:
```bash
[user@host dirac_dir]$ source diracos/diracosrc 
(base) [user@host dirac_dir]$
```

On RHEL PS1 is not exported by the system-wide bashrc, for some reason this upsets v2.34 but not earlier versions (Running "export PS1" is a workaround). I imagine something has changed upstream, but it wasn't obvious to me what and I couldn't find any bug reports for this. Any ideas?

Regards,
Simon

**Comment by chrisburr** [comment]
I'm pretty sure this is coming from the change of micromamba version.

I presume it's a cosmetic issue? Or is it enough of a problem that justifies rolling back to the previous micromamba version while I debug?

**Comment by chrisburr** [comment]
Reported here: https://github.com/mamba-org/mamba/issues/2659

**Comment by chrisburr** [comment]
I think I have a solution in https://github.com/DIRACGrid/DIRACOS2/pull/112
