### ISSUE TITLE
Add other owners to the diracgrid conda channel

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/DIRACOS2#2]
Currently I'm the only owner of https://anaconda.org/diracgrid/.

@fstagni Can you make an account, or assign someone else to, so that there can be at least two people with access?

**Comment by fstagni** [comment]
I am user `fstagni` there. Maybe @atsareg also wants access?

**Comment by atsareg** [comment]
Yes, please

**Comment by chrisburr** [comment]
@atsareg Can you make an account on https://anaconda.org and share the username?

**Comment by chrisburr** [comment]
Ping @atsareg

**Comment by atsareg** [comment]
I have already created atsareg account in the https://anaconda.org. I thought I have sent you a message on that but may be I didn't...

**Comment by chrisburr** [comment]
Maybe I missed it somewhere regardless, you've been added now. Thanks!
