### ISSUE TITLE
Add rucio-clients

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/DIRACOS2#22]
As this is in DIRACOS it should probably also be added to DIRACOS2. Some pointers for whoever wants to do this:

* It needs to be added to conda-forge via [staged-recipes](https://github.com/conda-forge/staged-recipes/#getting-started)
* The recipe itself can be mostly generated by grayskull, there is an online version of it [here](https://www.marcelotrevisani.com/grayskull)
* Once the PR is ready someone can ping me on it to review/merge
* Finally, it can be added to the list of `specs` in https://github.com/DIRACGrid/DIRACOS2/blob/main/construct.yaml

A couple of useful tutorials:
* Official docs: https://conda-forge.org/docs/maintainer/adding_pkgs.html
* Very detailed step-by-step blog post: https://gallon.me/3-simple-steps-to-build-a-python-package-for-conda-forge/

**Comment by chrisburr** [comment]
@cserf Just reminding you about this

**Comment by fstagni** [comment]
Just linking https://github.com/rucio/rucio/issues/4671

As of now, since we merged the original Rucio PR in DIRAC, the DIRAC integration tests for Python3 server are failing, because `rucio` is not in conda-forge (nor DIRACOS2). So, this becomes now higher priority.

**Comment by chrisburr** [comment]
Ping @cserf, we now have a non-prerelease of DIRAC that is supposed to support Python 3 and Rucio but the client libraries aren't shipped so it won't actually work
