### ISSUE TITLE
[discussion] oidc-agent package

### ISSUE THREAD

**Issue by TaykYoku** [DIRACGrid/DIRACOS2#40]
I am currently testing the ability to use an [oidc-agent](https://github.com/indigo-dc/oidc-agent#installation) for a DIRAC Client installation. I'm wondering if there may be any caveats about adding a this package installation, and how to properly add it to a client installation?
It also has a python library [liboidcagent](https://github.com/indigo-dc/liboidc-agent-py#liboidcagent) to communicate with the oidc-agent through UNIX domain sockets.

**Comment by petricm** [comment]
Having a quick look seems there is an srpm for el7, so jamming this in is theoretically possible, but probably very painful. I would deffer this to DIRACOS2.

**Comment by chrisburr** [comment]
I've made a PR to add it to conda-forge here: https://github.com/conda-forge/staged-recipes/pull/15217 and I've uploaded it to my personal channel in case you want to test it sooner (`mamba install -c chrisburr oidc-server`).

> I'm wondering if there may be any caveats about adding a this package installation, and how to properly add it to a client installation?

The main caveat I see is that it's not possible to get this as part of `pip install DIRAC` so it will make client installation harder. That said this is already partially the case as voms and gfal2 have to be installed manually. It's also not a problem for anyone installing DIRAC from conda-forge.

For my curiosity, what is the reason for wanting to use it?

**Comment by chrisburr** [comment]
You can also now download a DIRACOS2 installer from if you want to test it directly from the bottom of: https://github.com/DIRACGrid/DIRACOS2/actions/runs/921728537

I won't merge #41 until it's decided if `oidc-agent` is definitely going to be used.

**Comment by TaykYoku** [comment]
thanks for the quick response and clarification, but please, don't add it anywhere yet, unless it's needed for some other purpose.  thanks
