### ISSUE TITLE
Add sphinx-rtd-theme, sphinx-panels

### ISSUE THREAD

**Issue by TaykYoku** [DIRACGrid/DIRACOS2#48]
Based on the discussion in [#5313](https://github.com/DIRACGrid/DIRAC/pull/5313) raised by  [#5309](https://github.com/DIRACGrid/DIRAC/issues/5309) issue, it seems that the RTD theme can be applied in the new release. The following packages are used in it:

[sphinx-rtd-theme](https://sphinx-rtd-theme.readthedocs.io/en/latest/installing.html#installation)
[sphinx-panels](https://sphinx-panels.readthedocs.io/en/latest/#installation)

**Comment by chrisburr** [comment]
I don't think we need these in DIRACOS do we as they're only used by the CI?

**Comment by TaykYoku** [comment]
It works without this action, so if it is not necessary, I think we can close this issue.
